language: ruby

rvm:
 - 2.3.0

services:
 - postgresql

test:
  adapter: postgresql
  database: travis_ci_test

script: bundle exec rspec spec

before_install:
  - cp config/database.yml.travis config/database.yml