language: ruby

sudo: false

services:
  - postgresql

cache:
  directories:
    - vendor/bundle

rvm: "2.3.0"

env:
  - RAILS_ENV=test

matrix:
include:
  - addons:
      postgresql: "9.6"
fast_finish: true

before_install:
  - gem install bundler

install:
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:schema:load